---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: b-routes
  namespace: bookinfo
  labels:
    domain: 'demo.mtritaba.com'
spec:
  routes:
  - matchers:
     # the path matchers in this RouteTable can begin with any prefix
    - prefix: /app-b
    routeAction:
      single:
        upstream:
          name: bookinfo-productpage-static-9080
          namespace: gloo-system
    options:
      prefixRewrite: '/'
